import type { Metadata } from "next";
import {Providers} from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Imobiliária HW",
  description: "Generated by create next app",
  icons: {
    icon: 'Logo 1.svg'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body>
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
